// <auto-generated />
namespace LIMSData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FileUploadLogs_v16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileUploadLogs_v16));
        
        string IMigrationMetadata.Id
        {
            get { return "201806101759097_FileUploadLogs_v1.6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
