// <auto-generated />
namespace LIMSData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PARequests_V4_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PARequests_V4_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201805240126303_PARequests_V4_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
